# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/trojan
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Surge.conf

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
    url: https://raw.githubusercontent.com/mzh058/chenx/main/clash 

# 某个网站抓取
- type: web-freessrxyz
  options:
  
 
